name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: echo "No tests configured"

    - name: Build
      run: echo "No build step configured"

    - name: Start Server
      run: |
        npm start &
        sleep 10 # Tunggu sebentar agar server benar-benar berjalan
        curl -f http://localhost:3000 || exit 1
      env:
        PORT: 3000
